"""
Universal CV Terminology Dictionary
Covers all industries and professions, not specific to aviation
"""

def get_universal_cv_terminology():
    """Load comprehensive CV terminology dictionary for all industries"""
    return {
        "en_to_ar": {
            # Universal Job Titles
            "Manager": "مدير",
            "Senior Manager": "مدير أول",
            "Director": "مدير عام",
            "Executive Director": "مدير تنفيذي",
            "Chief Executive Officer": "الرئيس التنفيذي",
            "Chief Technology Officer": "مدير التكنولوجيا",
            "Chief Financial Officer": "المدير المالي",
            "Vice President": "نائب الرئيس",
            "President": "رئيس",
            "Head of": "رئيس",
            "Lead": "قائد",
            "Team Lead": "قائد الفريق",
            "Project Manager": "مدير المشروع",
            "Program Manager": "مدير البرنامج",
            "Product Manager": "مدير المنتج",
            "Operations Manager": "مدير العمليات",
            "Sales Manager": "مدير المبيعات",
            "Marketing Manager": "مدير التسويق",
            "HR Manager": "مدير الموارد البشرية",
            "Finance Manager": "المدير المالي",
            "IT Manager": "مدير تقنية المعلومات",
            "Quality Manager": "مدير الجودة",
            "Business Manager": "مدير الأعمال",
            "Regional Manager": "المدير الإقليمي",
            "General Manager": "المدير العام",
            "Assistant Manager": "مساعد مدير",
            "Deputy Manager": "نائب المدير",
            
            # Professional Roles
            "Consultant": "استشاري",
            "Senior Consultant": "استشاري أول",
            "Advisor": "مستشار",
            "Senior Advisor": "مستشار أول",
            "Specialist": "أخصائي",
            "Senior Specialist": "أخصائي أول",
            "Expert": "خبير",
            "Senior Expert": "خبير أول",
            "Analyst": "محلل",
            "Senior Analyst": "محلل أول",
            "Coordinator": "منسق",
            "Senior Coordinator": "منسق أول",
            "Supervisor": "مشرف",
            "Senior Supervisor": "مشرف أول",
            "Officer": "موظف",
            "Senior Officer": "موظف أول",
            "Executive": "تنفيذي",
            "Senior Executive": "تنفيذي أول",
            "Associate": "شريك",
            "Senior Associate": "شريك أول",
            "Assistant": "مساعد",
            "Administrative Assistant": "مساعد إداري",
            "Executive Assistant": "مساعد تنفيذي",
            "Secretary": "سكرتير",
            "Receptionist": "موظف استقبال",
            
            # Technical Roles
            "Engineer": "مهندس",
            "Senior Engineer": "مهندس أول",
            "Software Engineer": "مهندس برمجيات",
            "System Engineer": "مهندس أنظمة",
            "Network Engineer": "مهندس شبكات",
            "Data Engineer": "مهندس بيانات",
            "DevOps Engineer": "مهندس DevOps",
            "Quality Assurance Engineer": "مهندس ضمان الجودة",
            "Test Engineer": "مهندس اختبار",
            "Support Engineer": "مهندس دعم",
            "Technical Lead": "قائد تقني",
            "Architect": "مهندس معماري",
            "Software Architect": "مهندس معماري للبرمجيات",
            "System Architect": "مهندس معماري للأنظمة",
            "Developer": "مطور",
            "Senior Developer": "مطور أول",
            "Full Stack Developer": "مطور متكامل",
            "Frontend Developer": "مطور واجهات أمامية",
            "Backend Developer": "مطور خلفي",
            "Mobile Developer": "مطور تطبيقات محمولة",
            "Web Developer": "مطور ويب",
            "Database Administrator": "مدير قاعدة البيانات",
            "System Administrator": "مدير النظام",
            "Network Administrator": "مدير الشبكة",
            "Security Administrator": "مدير الأمان",
            "DevOps Specialist": "أخصائي DevOps",
            "Cloud Specialist": "أخصائي الحوسبة السحابية",
            "Data Scientist": "عالم بيانات",
            "Data Analyst": "محلل بيانات",
            "Business Analyst": "محلل أعمال",
            "System Analyst": "محلل أنظمة",
            "Programmer": "مبرمج",
            "Senior Programmer": "مبرمج أول",
            
            # Healthcare Roles
            "Doctor": "طبيب",
            "Physician": "طبيب",
            "Surgeon": "جراح",
            "Nurse": "ممرض",
            "Pharmacist": "صيدلي",
            "Dentist": "طبيب أسنان",
            "Therapist": "معالج",
            "Radiologist": "أخصائي أشعة",
            "Laboratory Technician": "فني مختبر",
            "Medical Assistant": "مساعد طبي",
            "Healthcare Administrator": "مدير رعاية صحية",
            
            # Education Roles
            "Teacher": "معلم",
            "Professor": "أستاذ",
            "Assistant Professor": "أستاذ مساعد",
            "Associate Professor": "أستاذ مشارك",
            "Lecturer": "محاضر",
            "Instructor": "مدرب",
            "Principal": "مدير مدرسة",
            "Dean": "عميد",
            "Academic Coordinator": "منسق أكاديمي",
            "Research Assistant": "مساعد باحث",
            "Researcher": "باحث",
            "Senior Researcher": "باحث أول",
            
            # Finance & Banking
            "Accountant": "محاسب",
            "Senior Accountant": "محاسب أول",
            "Financial Analyst": "محلل مالي",
            "Investment Analyst": "محلل استثمار",
            "Credit Analyst": "محلل ائتمان",
            "Risk Analyst": "محلل مخاطر",
            "Auditor": "مدقق",
            "Internal Auditor": "مدقق داخلي",
            "External Auditor": "مدقق خارجي",
            "Tax Consultant": "مستشار ضريبي",
            "Financial Advisor": "مستشار مالي",
            "Investment Advisor": "مستشار استثمار",
            "Bank Manager": "مدير بنك",
            "Branch Manager": "مدير فرع",
            "Loan Officer": "موظف قروض",
            "Teller": "أمين صندوق",
            "Customer Service Representative": "ممثل خدمة العملاء",
            
            # Sales & Marketing
            "Sales Representative": "ممثل مبيعات",
            "Sales Executive": "تنفيذي مبيعات",
            "Account Manager": "مدير حساب",
            "Key Account Manager": "مدير حسابات رئيسية",
            "Business Development Manager": "مدير تطوير الأعمال",
            "Marketing Specialist": "أخصائي تسويق",
            "Digital Marketing Specialist": "أخصائي تسويق رقمي",
            "Social Media Manager": "مدير وسائل التواصل الاجتماعي",
            "Content Manager": "مدير المحتوى",
            "Brand Manager": "مدير العلامة التجارية",
            "Public Relations Manager": "مدير العلاقات العامة",
            "Customer Success Manager": "مدير نجاح العملاء",
            
            # Legal
            "Lawyer": "محامي",
            "Attorney": "محامي",
            "Legal Advisor": "مستشار قانوني",
            "Legal Counsel": "مستشار قانوني",
            "Paralegal": "مساعد قانوني",
            "Judge": "قاضي",
            "Legal Assistant": "مساعد قانوني",
            
            # Industries & Sectors
            "Technology": "التكنولوجيا",
            "Information Technology": "تقنية المعلومات",
            "Software": "البرمجيات",
            "Hardware": "الأجهزة",
            "Telecommunications": "الاتصالات",
            "Healthcare": "الرعاية الصحية",
            "Education": "التعليم",
            "Finance": "المالية",
            "Banking": "المصرفية",
            "Insurance": "التأمين",
            "Real Estate": "العقارات",
            "Construction": "البناء",
            "Manufacturing": "التصنيع",
            "Automotive": "السيارات",
            "Energy": "الطاقة",
            "Oil and Gas": "النفط والغاز",
            "Retail": "التجزئة",
            "E-commerce": "التجارة الإلكترونية",
            "Hospitality": "الضيافة",
            "Tourism": "السياحة",
            "Transportation": "النقل",
            "Logistics": "اللوجستيات",
            "Supply Chain": "سلسلة التوريد",
            "Media": "الإعلام",
            "Entertainment": "الترفيه",
            "Sports": "الرياضة",
            "Non-profit": "غير ربحي",
            "Government": "الحكومة",
            "Public Sector": "القطاع العام",
            "Private Sector": "القطاع الخاص",
            "Consulting": "الاستشارات",
            "Research": "البحث",
            "Development": "التطوير",
            
            # Skills & Competencies
            "Leadership": "القيادة",
            "Management": "الإدارة",
            "Communication": "التواصل",
            "Problem Solving": "حل المشكلات",
            "Critical Thinking": "التفكير النقدي",
            "Analytical Thinking": "التفكير التحليلي",
            "Strategic Thinking": "التفكير الاستراتيجي",
            "Creative Thinking": "التفكير الإبداعي",
            "Decision Making": "اتخاذ القرارات",
            "Team Management": "إدارة الفريق",
            "Project Management": "إدارة المشاريع",
            "Time Management": "إدارة الوقت",
            "Stress Management": "إدارة الضغط",
            "Conflict Resolution": "حل النزاعات",
            "Negotiation": "التفاوض",
            "Presentation": "العرض",
            "Public Speaking": "الخطابة",
            "Customer Service": "خدمة العملاء",
            "Sales": "المبيعات",
            "Marketing": "التسويق",
            "Innovation": "الابتكار",
            "Creativity": "الإبداع",
            "Adaptability": "القدرة على التكيف",
            "Flexibility": "المرونة",
            "Teamwork": "العمل الجماعي",
            "Collaboration": "التعاون",
            "Networking": "التواصل المهني",
            "Mentoring": "التوجيه",
            "Training": "التدريب",
            "Coaching": "التدريب",
            "Quality Assurance": "ضمان الجودة",
            "Quality Control": "مراقبة الجودة",
            "Process Improvement": "تحسين العمليات",
            "Change Management": "إدارة التغيير",
            "Risk Management": "إدارة المخاطر",
            "Budget Management": "إدارة الميزانية",
            "Financial Planning": "التخطيط المالي",
            "Strategic Planning": "التخطيط الاستراتيجي",
            "Business Planning": "تخطيط الأعمال",
            "Market Research": "بحوث السوق",
            "Data Analysis": "تحليل البيانات",
            "Statistical Analysis": "التحليل الإحصائي",
            "Research": "البحث",
            "Documentation": "التوثيق",
            "Reporting": "إعداد التقارير",
            "Writing": "الكتابة",
            "Editing": "التحرير",
            "Proofreading": "التدقيق اللغوي",
            "Translation": "الترجمة",
            "Interpretation": "الترجمة الفورية",
            
            # Technical Skills
            "Programming": "البرمجة",
            "Software Development": "تطوير البرمجيات",
            "Web Development": "تطوير الويب",
            "Mobile Development": "تطوير التطبيقات المحمولة",
            "Database Management": "إدارة قواعد البيانات",
            "System Administration": "إدارة الأنظمة",
            "Network Administration": "إدارة الشبكات",
            "Cybersecurity": "الأمن السيبراني",
            "Information Security": "أمن المعلومات",
            "Cloud Computing": "الحوسبة السحابية",
            "Artificial Intelligence": "الذكاء الاصطناعي",
            "Machine Learning": "التعلم الآلي",
            "Data Science": "علم البيانات",
            "Big Data": "البيانات الضخمة",
            "Business Intelligence": "ذكاء الأعمال",
            "Digital Marketing": "التسويق الرقمي",
            "Social Media Marketing": "تسويق وسائل التواصل الاجتماعي",
            "Search Engine Optimization": "تحسين محركات البحث",
            "Content Management": "إدارة المحتوى",
            "Graphic Design": "التصميم الجرافيكي",
            "User Experience Design": "تصميم تجربة المستخدم",
            "User Interface Design": "تصميم واجهة المستخدم",
            "Video Editing": "تحرير الفيديو",
            "Photography": "التصوير",
            "Audio Production": "إنتاج الصوت",
            
            # Education
            "Bachelor": "بكالوريوس",
            "Bachelor's Degree": "درجة البكالوريوس",
            "Master": "ماجستير",
            "Master's Degree": "درجة الماجستير",
            "PhD": "دكتوراه",
            "Doctorate": "دكتوراه",
            "Diploma": "دبلوم",
            "Certificate": "شهادة",
            "Certification": "شهادة",
            "License": "رخصة",
            "Professional Certificate": "شهادة مهنية",
            "Training Course": "دورة تدريبية",
            "Workshop": "ورشة عمل",
            "Seminar": "ندوة",
            "Conference": "مؤتمر",
            "University": "جامعة",
            "College": "كلية",
            "Institute": "معهد",
            "Academy": "أكاديمية",
            "School": "مدرسة",
            
            # Fields of Study
            "Engineering": "الهندسة",
            "Computer Science": "علوم الحاسوب",
            "Information Technology": "تقنية المعلومات",
            "Business Administration": "إدارة الأعمال",
            "Finance": "المالية",
            "Accounting": "المحاسبة",
            "Economics": "الاقتصاد",
            "Marketing": "التسويق",
            "Management": "الإدارة",
            "Human Resources": "الموارد البشرية",
            "Psychology": "علم النفس",
            "Sociology": "علم الاجتماع",
            "Political Science": "العلوم السياسية",
            "International Relations": "العلاقات الدولية",
            "Law": "القانون",
            "Medicine": "الطب",
            "Nursing": "التمريض",
            "Pharmacy": "الصيدلة",
            "Dentistry": "طب الأسنان",
            "Architecture": "العمارة",
            "Civil Engineering": "الهندسة المدنية",
            "Mechanical Engineering": "الهندسة الميكانيكية",
            "Electrical Engineering": "الهندسة الكهربائية",
            "Chemical Engineering": "الهندسة الكيميائية",
            "Industrial Engineering": "الهندسة الصناعية",
            "Software Engineering": "هندسة البرمجيات",
            "Mathematics": "الرياضيات",
            "Physics": "الفيزياء",
            "Chemistry": "الكيمياء",
            "Biology": "الأحياء",
            "Environmental Science": "العلوم البيئية",
            "Geography": "الجغرافيا",
            "History": "التاريخ",
            "Literature": "الأدب",
            "Languages": "اللغات",
            "Education": "التعليم",
            "Art": "الفن",
            "Music": "الموسيقى",
            "Sports Science": "علوم الرياضة",
            "Journalism": "الصحافة",
            "Mass Communication": "الاتصال الجماهيري",
            "Public Relations": "العلاقات العامة",
            "Advertising": "الإعلان",
            
            # Locations (UAE specific but can be extended)
            "Abu Dhabi": "أبوظبي",
            "Dubai": "دبي",
            "Sharjah": "الشارقة",
            "Ajman": "عجمان",
            "Fujairah": "الفجيرة",
            "Ras Al Khaimah": "رأس الخيمة",
            "Umm Al Quwain": "أم القيوين",
            "UAE": "الإمارات العربية المتحدة",
            "United Arab Emirates": "الإمارات العربية المتحدة",
            
            # Common Terms
            "Present": "الحاضر",
            "Current": "الحالي",
            "Experience": "الخبرة",
            "Work Experience": "الخبرة العملية",
            "Professional Experience": "الخبرة المهنية",
            "Education": "التعليم",
            "Academic Background": "الخلفية الأكاديمية",
            "Skills": "المهارات",
            "Technical Skills": "المهارات التقنية",
            "Soft Skills": "المهارات الشخصية",
            "Languages": "اللغات",
            "Certifications": "الشهادات",
            "Projects": "المشاريع",
            "Achievements": "الإنجازات",
            "Awards": "الجوائز",
            "Honors": "التكريمات",
            "Publications": "المنشورات",
            "References": "المراجع",
            "Responsibilities": "المسؤوليات",
            "Duties": "الواجبات",
            "Tasks": "المهام",
            "Accomplishments": "الإنجازات",
            "Results": "النتائج",
            "Outcomes": "المخرجات",
            "Impact": "التأثير",
            "Contribution": "المساهمة",
            "Role": "الدور",
            "Position": "المنصب",
            "Job Title": "المسمى الوظيفي",
            "Company": "الشركة",
            "Organization": "المنظمة",
            "Institution": "المؤسسة",
            "Department": "القسم",
            "Division": "الشعبة",
            "Team": "الفريق",
            "Group": "المجموعة",
            "Unit": "الوحدة",
            "Branch": "الفرع",
            "Office": "المكتب",
            "Location": "الموقع",
            "Address": "العنوان",
            "Contact": "الاتصال",
            "Phone": "الهاتف",
            "Mobile": "الجوال",
            "Email": "البريد الإلكتروني",
            "Website": "الموقع الإلكتروني",
            "LinkedIn": "لينكد إن",
            "Portfolio": "المحفظة",
            "Profile": "الملف الشخصي",
            "Summary": "الملخص",
            "Objective": "الهدف",
            "Career Objective": "الهدف المهني",
            "Professional Summary": "الملخص المهني",
            "Personal Information": "المعلومات الشخصية",
            "Contact Information": "معلومات الاتصال",
            "Full Name": "الاسم الكامل",
            "First Name": "الاسم الأول",
            "Last Name": "اسم العائلة",
            "Date of Birth": "تاريخ الميلاد",
            "Nationality": "الجنسية",
            "Gender": "الجنس",
            "Marital Status": "الحالة الاجتماعية",
            "Visa Status": "حالة التأشيرة",
            "Work Permit": "تصريح العمل",
            "Availability": "التوفر",
            "Notice Period": "فترة الإشعار",
            "Salary Expectation": "التوقع المالي",
            "Expected Salary": "الراتب المتوقع",
            "Current Salary": "الراتب الحالي",
            "Benefits": "المزايا",
            "Bonus": "المكافأة",
            "Commission": "العمولة",
            "Overtime": "العمل الإضافي",
            "Vacation": "الإجازة",
            "Sick Leave": "الإجازة المرضية",
            "Health Insurance": "التأمين الصحي",
            "Life Insurance": "تأمين الحياة",
            "Retirement Plan": "خطة التقاعد",
            "Stock Options": "خيارات الأسهم",
            "Training": "التدريب",
            "Professional Development": "التطوير المهني",
            "Career Development": "التطوير الوظيفي",
            "Promotion": "الترقية",
            "Transfer": "النقل",
            "Resignation": "الاستقالة",
            "Termination": "الإنهاء",
            "Retirement": "التقاعد",
            "Contract": "العقد",
            "Full-time": "دوام كامل",
            "Part-time": "دوام جزئي",
            "Temporary": "مؤقت",
            "Permanent": "دائم",
            "Freelance": "عمل حر",
            "Consultant": "استشاري",
            "Contractor": "متعاقد",
            "Intern": "متدرب",
            "Trainee": "متدرب",
            "Volunteer": "متطوع",
            "Remote": "عن بُعد",
            "On-site": "في الموقع",
            "Hybrid": "مختلط",
            "Flexible": "مرن",
            "Shift Work": "عمل بنظام الورديات",
            "Night Shift": "الوردية الليلية",
            "Day Shift": "الوردية النهارية",
            "Weekend": "نهاية الأسبوع",
            "Holiday": "العطلة",
            "Public Holiday": "العطلة الرسمية",
            "Annual Leave": "الإجازة السنوية",
            "Maternity Leave": "إجازة الأمومة",
            "Paternity Leave": "إجازة الأبوة",
            "Study Leave": "إجازة دراسية",
            "Sabbatical": "إجازة تفرغ",
            "Performance Review": "تقييم الأداء",
            "Appraisal": "التقييم",
            "Feedback": "التغذية الراجعة",
            "Goal Setting": "وضع الأهداف",
            "KPI": "مؤشرات الأداء الرئيسية",
            "Metrics": "المقاييس",
            "Targets": "الأهداف",
            "Objectives": "الأهداف",
            "Milestones": "المعالم",
            "Deadlines": "المواعيد النهائية",
            "Timeline": "الجدول الزمني",
            "Schedule": "الجدولة",
            "Planning": "التخطيط",
            "Execution": "التنفيذ",
            "Implementation": "التطبيق",
            "Monitoring": "المراقبة",
            "Evaluation": "التقييم",
            "Review": "المراجعة",
            "Analysis": "التحليل",
            "Assessment": "التقييم",
            "Audit": "التدقيق",
            "Inspection": "التفتيش",
            "Quality": "الجودة",
            "Standards": "المعايير",
            "Procedures": "الإجراءات",
            "Policies": "السياسات",
            "Guidelines": "الإرشادات",
            "Best Practices": "أفضل الممارسات",
            "Methodology": "المنهجية",
            "Framework": "الإطار",
            "Model": "النموذج",
            "System": "النظام",
            "Process": "العملية",
            "Workflow": "سير العمل",
            "Protocol": "البروتوكول",
            "Standard Operating Procedure": "إجراء التشغيل المعياري",
            "SOP": "إجراء التشغيل المعياري",
            "Documentation": "التوثيق",
            "Manual": "الدليل",
            "Handbook": "كتيب",
            "Guide": "الدليل",
            "Instructions": "التعليمات",
            "Specifications": "المواصفات",
            "Requirements": "المتطلبات",
            "Criteria": "المعايير",
            "Conditions": "الشروط",
            "Terms": "الشروط",
            "Agreement": "الاتفاقية",
            "Contract": "العقد",
            "Deal": "الصفقة",
            "Partnership": "الشراكة",
            "Collaboration": "التعاون",
            "Alliance": "التحالف",
            "Joint Venture": "المشروع المشترك",
            "Merger": "الاندماج",
            "Acquisition": "الاستحواذ",
            "Investment": "الاستثمار",
            "Funding": "التمويل",
            "Capital": "رأس المال",
            "Revenue": "الإيرادات",
            "Profit": "الربح",
            "Loss": "الخسارة",
            "Budget": "الميزانية",
            "Cost": "التكلفة",
            "Expense": "المصروف",
            "Income": "الدخل",
            "Salary": "الراتب",
            "Wage": "الأجر",
            "Fee": "الرسوم",
            "Commission": "العمولة",
            "Bonus": "المكافأة",
            "Incentive": "الحافز",
            "Reward": "المكافأة",
            "Recognition": "التقدير",
            "Appreciation": "التقدير",
            "Acknowledgment": "الاعتراف",
            "Credit": "الائتمان",
            "Achievement": "الإنجاز",
            "Success": "النجاح",
            "Excellence": "التميز",
            "Outstanding": "متميز",
            "Exceptional": "استثنائي",
            "Superior": "متفوق",
            "High Performance": "الأداء العالي",
            "Top Performer": "أفضل أداء",
            "Star Employee": "الموظف النجم",
            "Employee of the Month": "موظف الشهر",
            "Employee of the Year": "موظف السنة",
            "Leadership Award": "جائزة القيادة",
            "Innovation Award": "جائزة الابتكار",
            "Quality Award": "جائزة الجودة",
            "Safety Award": "جائزة السلامة",
            "Customer Service Award": "جائزة خدمة العملاء",
            "Team Player Award": "جائزة روح الفريق",
            "Dedication Award": "جائزة التفاني",
            "Commitment Award": "جائزة الالتزام",
            "Loyalty Award": "جائزة الولاء",
            "Long Service Award": "جائزة الخدمة الطويلة",
            "Retirement Award": "جائزة التقاعد",
            "Scholarship": "المنحة الدراسية",
            "Grant": "المنحة",
            "Fellowship": "الزمالة",
            "Sponsorship": "الرعاية",
            "Endorsement": "التأييد",
            "Recommendation": "التوصية",
            "Reference": "المرجع",
            "Testimonial": "الشهادة",
            "Letter of Recommendation": "خطاب توصية",
            "Character Reference": "مرجع شخصي",
            "Professional Reference": "مرجع مهني",
            "Academic Reference": "مرجع أكاديمي",
            "Personal Reference": "مرجع شخصي"
        }
    }

# Create reverse mapping for Arabic to English
def create_reverse_mapping(terminology_dict):
    """Create reverse mapping from Arabic to English"""
    en_to_ar = terminology_dict["en_to_ar"]
    ar_to_en = {}
    
    for en_term, ar_term in en_to_ar.items():
        ar_to_en[ar_term] = en_term
    
    terminology_dict["ar_to_en"] = ar_to_en
    return terminology_dict

# Get complete universal terminology
def get_complete_universal_terminology():
    """Get complete universal CV terminology with reverse mapping"""
    terminology = get_universal_cv_terminology()
    return create_reverse_mapping(terminology)

