-- 090_outbound_mail_delegation.sql
--
-- WHY
--
-- Per-message approval (migration 088) was right for the first five sends and
-- wrong for four hundred. An owner clicking approve on four hundred renderings
-- of one template is not reviewing them; it is rubber-stamping, which is worse
-- than no review because it looks like governance and produces a signature.
--
-- Owner's decision, 2026-08-26: "I don't want to be the bottleneck. I would let
-- the agents do their job, but I need a mechanism where I can audit and verify
-- the quality of the operation."
--
-- So the unit of the owner's attention moves from the MESSAGE to the TEMPLATE:
--
--   * The owner approves the wording of a message KIND once.
--   * Operators release individual messages that render from it.
--   * A message that does NOT match an approved template still needs
--     per-message approval, so one-offs keep the strict path of migration 088.
--
-- HOW WE KNOW A MESSAGE "MATCHES" AN APPROVED TEMPLATE
--
-- Bodies are generated by code, so an approval of wording is only meaningful if
-- editing that code invalidates it. Each template row stores a FINGERPRINT: the
-- hash of a probe rendering with fixed placeholder values. At release time the
-- probe is re-rendered and compared. Change the template function and the
-- fingerprint moves, the match fails, and the messages fall back to needing the
-- owner — which is the safe direction, and it happens without anyone having to
-- remember to re-approve.
--
-- ONLY ONE VERSION OF A KIND IS APPROVED AT A TIME (partial unique index), so
-- "which wording did the owner sign off" always has one answer.
--
-- THE GUARDRAILS
--
-- A per-operator daily cap means one mistake cannot become four hundred emails.
-- A pause flag lets a run stop itself — on a surge of never-before-seen
-- recipient domains, or a spike in send failures — and requires an
-- administrator to resume, so a bad run halts rather than waiting to be
-- noticed. Both live in a single-row control table an admin can change without
-- a deploy.
--
-- PRECONDITION VERIFIED ON THE LIVE DB 2026-08-26
--   outbound_mail exists (migration 088) with status
--     ('held','approved','sending','sent','failed','rejected')
--   0 rows in outbound_mail — the test messages were cleaned up
--   no table named outbound_mail_templates or outbound_mail_controls

BEGIN;

-- ── What the owner approves ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS outbound_mail_templates (
    id              BIGSERIAL PRIMARY KEY,
    kind            TEXT        NOT NULL,
    version         INTEGER     NOT NULL,

    -- Hash of a probe rendering. Editing the template function moves this, and
    -- the approval stops matching. See the module docstring above.
    fingerprint     TEXT        NOT NULL,

    -- What the owner actually read when approving. Stored rather than
    -- re-rendered later, so the record shows the wording as it was signed off
    -- even after the code has moved on.
    sample_subject  TEXT        NOT NULL,
    sample_body     TEXT        NOT NULL,

    status          TEXT        NOT NULL DEFAULT 'pending',
    note            TEXT,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_by     CHAR(15),
    approved_at     TIMESTAMPTZ,
    retired_at      TIMESTAMPTZ,

    CONSTRAINT outbound_mail_templates_kind_version_key UNIQUE (kind, version),
    CONSTRAINT outbound_mail_templates_status_chk
        CHECK (status IN ('pending', 'approved', 'retired')),
    -- An approved template must name who approved it. Without this,
    -- "approved by nobody" is representable and delegation means nothing.
    CONSTRAINT outbound_mail_templates_approver_chk
        CHECK (status <> 'approved' OR approved_by IS NOT NULL)
);

-- One approved version per kind, so "which wording did the owner sign off"
-- has exactly one answer.
CREATE UNIQUE INDEX IF NOT EXISTS idx_outbound_mail_templates_one_approved
    ON outbound_mail_templates (kind)
 WHERE status = 'approved';

CREATE INDEX IF NOT EXISTS idx_outbound_mail_templates_fingerprint
    ON outbound_mail_templates (fingerprint)
 WHERE status = 'approved';

-- ── What a message records about how it was authorised ─────────────────────
ALTER TABLE outbound_mail
    ADD COLUMN IF NOT EXISTS template_fingerprint TEXT,
    ADD COLUMN IF NOT EXISTS release_basis        TEXT,
    ADD COLUMN IF NOT EXISTS released_by          CHAR(15),
    ADD COLUMN IF NOT EXISTS released_at          TIMESTAMPTZ;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                    WHERE conname = 'outbound_mail_release_basis_chk') THEN
        ALTER TABLE outbound_mail ADD CONSTRAINT outbound_mail_release_basis_chk
            CHECK (release_basis IS NULL
                   OR release_basis IN ('per_message', 'template'));
    END IF;
END $$;

COMMENT ON COLUMN outbound_mail.release_basis IS
    'per_message = an administrator read this exact message and approved it '
    '(migration 088). template = it rendered from a template whose wording the '
    'owner approved, and an operator released it (migration 090). NULL until '
    'authorised. This is the column an audit reads to ask "on what authority '
    'did this leave".';

COMMENT ON COLUMN outbound_mail.template_fingerprint IS
    'Fingerprint of the template that produced this body, recorded at compose '
    'time. Compared against the approved template at release time so a code '
    'change to the wording invalidates the approval automatically.';

CREATE INDEX IF NOT EXISTS idx_outbound_mail_released
    ON outbound_mail (released_by, released_at)
 WHERE released_by IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_outbound_mail_audit
    ON outbound_mail (kind, status, sent_at DESC);

-- ── The guardrails ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS outbound_mail_controls (
    id                 INTEGER     PRIMARY KEY DEFAULT 1,
    daily_release_cap  INTEGER     NOT NULL DEFAULT 500,
    paused             BOOLEAN     NOT NULL DEFAULT FALSE,
    pause_reason       TEXT,
    paused_at          TIMESTAMPTZ,
    resumed_by         CHAR(15),
    resumed_at         TIMESTAMPTZ,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT outbound_mail_controls_single_row CHECK (id = 1),
    CONSTRAINT outbound_mail_controls_cap_positive CHECK (daily_release_cap > 0),
    -- A pause must say why. "Paused" with no reason is a dead end for whoever
    -- finds it, and they are the person deciding whether to resume.
    CONSTRAINT outbound_mail_controls_pause_reason
        CHECK (NOT paused OR pause_reason IS NOT NULL)
);

INSERT INTO outbound_mail_controls (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

COMMENT ON TABLE outbound_mail_controls IS
    'Single row. daily_release_cap is PER OPERATOR per day — one mistake must '
    'not become four hundred emails. paused stops all releasing until an '
    'administrator resumes; it is set automatically when a run looks wrong '
    '(a surge of unseen recipient domains, or a spike in send failures) so a '
    'bad run halts itself rather than waiting to be noticed.';

COMMIT;

-- ── Verification ────────────────────────────────────────────────────────────
--
-- 1. Everything exists:
--      SELECT count(*) FROM information_schema.tables
--       WHERE table_name IN ('outbound_mail_templates','outbound_mail_controls');  -- 2
--      SELECT count(*) FROM outbound_mail_controls;                                -- 1
--      SELECT column_name FROM information_schema.columns
--       WHERE table_name='outbound_mail'
--         AND column_name IN ('template_fingerprint','release_basis',
--                             'released_by','released_at');                        -- 4
--
-- 2. Only one approved version per kind. Second insert must FAIL:
--      BEGIN;
--        INSERT INTO outbound_mail_templates
--               (kind,version,fingerprint,sample_subject,sample_body,status,approved_by,approved_at)
--        VALUES ('zz_probe',1,'fp1','s','b','approved','784000000000020',now());
--        INSERT INTO outbound_mail_templates
--               (kind,version,fingerprint,sample_subject,sample_body,status,approved_by,approved_at)
--        VALUES ('zz_probe',2,'fp2','s','b','approved','784000000000020',now());  -- must FAIL
--      ROLLBACK;
--
-- 3. An approved template with no approver must FAIL:
--      BEGIN;
--        INSERT INTO outbound_mail_templates
--               (kind,version,fingerprint,sample_subject,sample_body,status)
--        VALUES ('zz_probe',1,'fp','s','b','approved');                            -- must FAIL
--      ROLLBACK;
--
-- 4. A pause with no reason must FAIL:
--      BEGIN;
--        UPDATE outbound_mail_controls SET paused = TRUE WHERE id = 1;             -- must FAIL
--      ROLLBACK;
--
-- 5. A nonsense release basis must FAIL:
--      BEGIN;
--        INSERT INTO outbound_mail (to_email,subject,body_text,kind,release_basis)
--        VALUES ('zz@ehrdc.gov.ae','s','b','probe','whatever');                    -- must FAIL
--      ROLLBACK;
